### PR TITLE
Added include guards + the missing AdaGFX_swap

### PR DESCRIPTION
**Pull request by jenschr**
Hi. I've added these missing bits to be able to compile. Feel free to add them to the main repo.

### CODE REVIEW

**Comment by davetcc** [comment]
Hi there, thanks for the great work,  please can one of the maintainers merge this pull request? I've now got several bug reports for this building up on my menu library. I'd actually come here to put in this very pull request based on several users feedback for tcMenu.

My menu library aside, any non-trivial project is likely to be hit by the missing multiple inclusion guards issue. Further, it's a non-breaking change to add the include guards with only up-side as far as I can see.

**Comment by JvanderKaaij** [comment]
Is anyone still around who can merge this in? It's still a problem.

**Comment by jenschr** [comment]
lol. after 7 years, I think nobody is in charge of this repository any more. Maybe @ladyada can assign someone? This is a very simple fix

**Comment by ladyada** [comment]
hiya i redid the changes since the PR was not mergable! 
please check out the HEAD, @tyeth please bump this library

https://github.com/adafruit/Adafruit_SSD1325_Library/actions/runs/7874239524/job/21483386209

**Pull request closed without merging**
